name: on-push-main

on:
  # run on push to main, but not on tag release
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'

jobs:
  deploy-docs:
    name: deploy docs to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install deps
        run: npm ci

      - name: build docs
        run: npm run build:docs

      - name: deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
